name: Build and Commit Assets

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  build-and-commit:
    name: Build and Commit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Permissions
        run: chmod -R a-x .
        
      - name: Echo LS
        run: ls
        
      - name: Install dependencies
        run: npm install  # Adjust this based on your project's requirements

      - name: Build assets
        run: npx vite build  # Adjust this based on your project's build command

      - name: Commit built assets
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "github-action@example.com"
          git add .
          git commit -m "Add built assets"
          git push origin ${{ github.event.pull_request.base.ref }}
