name: Build and Commit Assets

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  build-and-commit:
    name: Can Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: npm install  # Adjust this based on your project's requirements

      - name: Build assets
        run: npm run build  # Adjust this based on your project's build command
